/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texteditor;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Pavan Yekabote
 */
public class TitleDisplay extends javax.swing.JPanel {

    /**
     * Creates new form TitleDisplay
     */
    private TextEditor te;
    private int titleIndex=0;
    private Object titledisplay;
    public TitleDisplay(TextEditor te) {
        this.te=te;
        initComponents();
        titledisplay=this;
        this.setOpaque(false);
        titlelabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                te.tabpane.setSelectedIndex(te.tabpane.indexOfTabComponent((Component)titledisplay));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        titlelabel = new javax.swing.JLabel();
        closetabBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelabel.setBackground(new java.awt.Color(255, 255, 255));
        titlelabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        titlelabel.setToolTipText("");
        add(titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        closetabBtn.setBackground(new java.awt.Color(255, 255, 255));
        closetabBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        closetabBtn.setText("X");
        closetabBtn.setToolTipText("Close this tab - Ctrl+Alt+W");
        closetabBtn.setAlignmentY(0.0F);
        closetabBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        closetabBtn.setBorderPainted(false);
        closetabBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closetabBtn.setInheritsPopupMenu(true);
        closetabBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closetabBtn.setMaximumSize(new java.awt.Dimension(5, 5));
        closetabBtn.setMinimumSize(new java.awt.Dimension(5, 5));
        closetabBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        closetabBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closetabBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closetabBtnMouseExited(evt);
            }
        });
        closetabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closetabBtnActionPerformed(evt);
            }
        });
        add(closetabBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void closetabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closetabBtnActionPerformed
        Store.SelectedTabIndex=Store.SelectedTabTitleIndex;
        te.tasks.removeTabFile(te.file,te.editpane);
    }//GEN-LAST:event_closetabBtnActionPerformed

    private void closetabBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetabBtnMouseExited
        closetabBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_closetabBtnMouseExited

    private void closetabBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetabBtnMouseEntered
        closetabBtn.setForeground(Color.RED);
        Store.SelectedTabTitleIndex = te.tabpane.indexOfTabComponent(this);
//        System.out.println("Selected TabPanePoint:"+Store.SelectedTabIndex+" Button:"+Store.SelectedTabTitleIndex);
            new Tasks(te).fileIndexSelect();
    }//GEN-LAST:event_closetabBtnMouseEntered

        

    public void setTitle(String title)
    {
        this.titlelabel.setText(title);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closetabBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables
}
